const MIDICCNumbers = [
    {ccNumber: 0, ccName: 'Bank Select (coarse)'},
    {ccNumber: 1, ccName: 'Modulation Wheel (coarse)'},
    {ccNumber: 2, ccName: 'Breath controller (coarse)'},
    {ccNumber: 4, ccName: 'Foot Pedal (coarse)'},
    {ccNumber: 5, ccName: 'Portamento Time (coarse)'},
    {ccNumber: 6, ccName: 'Data Entry (coarse)'},
    {ccNumber: 7, ccName: 'Volume (coarse)'},
    {ccNumber: 8, ccName: 'Balance (coarse)'},
    {ccNumber: 10, ccName: 'Pan position (coarse)'},
    {ccNumber: 11, ccName: 'Expression (coarse)'},
    {ccNumber: 12, ccName: 'Effect Control 1 (coarse)'},
    {ccNumber: 13, ccName: 'Effect Control 2 (coarse)'},
    {ccNumber: 16, ccName: 'General Purpose Slider 1'},
    {ccNumber: 17, ccName: 'General Purpose Slider 2'},
    {ccNumber: 18, ccName: 'General Purpose Slider 3'},
    {ccNumber: 19, ccName: 'General Purpose Slider 4'},
    {ccNumber: 32, ccName: 'Bank Select (fine)'},
    {ccNumber: 33, ccName: 'Modulation Wheel (fine)'},
    {ccNumber: 34, ccName: 'Breath controller (fine)'},
    {ccNumber: 36, ccName: 'Foot Pedal (fine)'},
    {ccNumber: 37, ccName: 'Portamento Time (fine)'},
    {ccNumber: 38, ccName: 'Data Entry (fine)'},
    {ccNumber: 39, ccName: 'Volume (fine)'},
    {ccNumber: 40, ccName: 'Balance (fine)'},
    {ccNumber: 42, ccName: 'Pan position (fine)'},
    {ccNumber: 43, ccName: 'Expression (fine)'},
    {ccNumber: 44, ccName: 'Effect Control 1 (fine)'},
    {ccNumber: 45, ccName: 'Effect Control 2 (fine)'},
    {ccNumber: 64, ccName: 'Hold Pedal (on/off)'},
    {ccNumber: 65, ccName: 'Portamento (on/off)'},
    {ccNumber: 66, ccName: 'Sustenuto Pedal (on/off)'},
    {ccNumber: 67, ccName: 'Soft Pedal (on/off)'},
    {ccNumber: 68, ccName: 'Legato Pedal (on/off)'},
    {ccNumber: 69, ccName: 'Hold 2 Pedal (on/off)'},
    {ccNumber: 70, ccName: 'Sound Variation'},
    {ccNumber: 71, ccName: 'Sound Timbre'},
    {ccNumber: 72, ccName: 'Sound Release Time'},
    {ccNumber: 73, ccName: 'Sound Attack Time'},
    {ccNumber: 74, ccName: 'Sound Brightness'},
    {ccNumber: 75, ccName: 'Sound Control 6'},
    {ccNumber: 76, ccName: 'Sound Control 7'},
    {ccNumber: 77, ccName: 'Sound Control 8'},
    {ccNumber: 78, ccName: 'Sound Control 9'},
    {ccNumber: 79, ccName: 'Sound Control 10'},
    {ccNumber: 80, ccName: 'General Purpose Button 1 (on/off)'},
    {ccNumber: 81, ccName: 'General Purpose Button 2 (on/off)'},
    {ccNumber: 82, ccName: 'General Purpose Button 3 (on/off)'},
    {ccNumber: 83, ccName: 'General Purpose Button 4 (on/off)'},
    {ccNumber: 91, ccName: 'Effects Level'},
    {ccNumber: 92, ccName: 'Tremolo Level'},
    {ccNumber: 93, ccName: 'Chorus Level'},
    {ccNumber: 94, ccName: 'Celeste Level'},
    {ccNumber: 95, ccName: 'Phaser Level'},
    {ccNumber: 96, ccName: 'Data Button increment'},
    {ccNumber: 97, ccName: 'Data Button decrement'},
    {ccNumber: 98, ccName: 'Non-registered Parameter (fine)'},
    {ccNumber: 99, ccName: 'Non-registered Parameter (coarse)'},
    {ccNumber: 100, ccName: 'Registered Parameter (fine)'},
    {ccNumber: 101, ccName: 'Registered Parameter (coarse)'},
    {ccNumber: 120, ccName: 'All Sound Off'},
    {ccNumber: 121, ccName: 'All Controllers Off'},
    {ccNumber: 122, ccName: 'Local Keyboard (on/off)'},
    {ccNumber: 123, ccName: 'All Notes Off'},
    {ccNumber: 124, ccName: 'Omni Mode Off'},
    {ccNumber: 125, ccName: 'Omni Mode On'},
    {ccNumber: 126, ccName: 'Mono Operation'},
    {ccNumber: 127, ccName: 'Poly Operation'}];


function filterCCType(typeQuery) {
    return MIDICCNumbers.filter(function(el) {
        return el.ccNumber == typeQuery;
        });
}

export function findCCTypeByNumber (CCNumberToSearch) {
    return filterCCType(CCNumberToSearch);
}